spring:
  application:
    name: tools

  # 파일 업로드
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  # 정적 리소스 캐시 사용 안함 설정
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          no-store: true
          must-revalidate: true

  # OPEN AI 설정
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}


# BRAVE SEARCH API
bravesearch:
  api-key: ${BRAVE_SEARCH_API_KEY}

logging:
  level:
    org.springframework.ai.tool: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG