spring:
  application:
    name: mcp-server-stdio-datetime

  main:
    web-application-type: none  # 웹 서버 미사용 설정
    banner-mode: off           # 배너 출력 비활성화

  ai:
    mcp:
      server:
        name: mcp-server-stdio-datetime
        version: "0.0.1"

logging:
  file:
    name: mcp-server-stdio-datetime.log
  pattern:
    console: ""               # 콘솔 로그 출력 제거